-- Create the bookings table
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    guest_name TEXT NOT NULL,
    booking_date TIMESTAMP WITH TIME ZONE NOT NULL,
    notes TEXT,
    status TEXT DEFAULT 'pending'
);

-- Enable Row Level Security (RLS)
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- Allow anonymous access (Adjust policies as needed for production)
-- For a simple public booking form:
CREATE POLICY "Enable insert for all users" ON bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable select for all users" ON bookings FOR SELECT USING (true);
CREATE POLICY "Enable update for all users" ON bookings FOR UPDATE USING (true);
CREATE POLICY "Enable delete for all users" ON bookings FOR DELETE USING (true);
